# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
jobs:
  build_ios:
    name: Build-iOS
    runs-on: macos-latest
    strategy:
      matrix:
        Configuration: [Debug, Debug_Mock, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        clean: false
    - name: setup-xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: 6.12 # specify version in '<major>.<minor>' format
        xamarin-ios-version: 14 # specify version in '<major>' format
        xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
        xamarin-android-version: 11.2 # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
        xcode-version: 12 # set the latest available Xcode 11
    - name: iOS.${{ matrix.Configuration }}
      run: |
        msbuild ${{ github.workspace }}/Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }} /p:Platform=iPhoneSimulator -r
  build_android:
    name: Build-Android
    runs-on: macos-latest
    strategy:
      matrix:
        Configuration: [Debug, Debug_Mock, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        clean: false
    - name: setup-xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: 6.12 # specify version in '<major>.<minor>' format
        xamarin-ios-version: 14 # specify version in '<major>' format
        xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
        xamarin-android-version: 11.2 # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
        xcode-version: 12 # set the latest available Xcode 11
    - name: Android.${{ matrix.Configuration }}
      run: |
        msbuild ${{ github.workspace }}/Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj /t:Rebuild /p:Configuration=${{ matrix.Configuration }} -r
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        clean: false
    - name: setup-xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        mono-version: 6.12 # specify version in '<major>.<minor>' format
        xamarin-ios-version: 14 # specify version in '<major>' format
        xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
        xamarin-android-version: 11.2 # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
        xcode-version: 12 # set the latest available Xcode 11
    - name: Prepare Xamarin
      run: |
        dotnet restore ${{ github.workspace }}/Covid19Radar.sln
    - name: Tests
      run: |
        dotnet test ${{ github.workspace }}/Covid19Radar/Tests/Covid19Radar.UnitTests/
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true