name: Infrastructure
on: pull_request
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: fmt
          tf_actions_working_dir: infrastructure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: init
          tf_actions_working_dir: infrastructure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: validate
          tf_actions_working_dir: infrastructure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
